create table tasks(
    id bigint primary key generated by default as identity,
    title varchar,
    description varchar,
    userId bigint
);

insert into tasks(title, description, userId) values ('task1', 'task1 desc', 1);
insert into tasks(title, description, userId) values ('task2', 'task2 desc', 2);