create table tasks(
    id bigint primary key generated by default as identity,
    title varchar,
    description varchar,
    user_id bigint,
    status varchar
);

insert into tasks(title, description, user_id, status) values ('task1', 'task1 desc', 1, 'NEW');
insert into tasks(title, description, user_id, status) values ('task2', 'task2 desc', 2, 'NEW');