create table tasks(
    id bigint primary key generated by default as identity,
    title varchar,
    description varchar,
    user_id bigint
);

insert into tasks(title, description, user_id) values ('task1', 'task1 desc', 1);
insert into tasks(title, description, user_id) values ('task2', 'task2 desc', 2);